### ISSUE TITLE
Order book depth should be increased

### ISSUE THREAD

**Issue by Klapeyron** [bigshortbets/market-frontend#56]

**Comment by Klapeyron** [comment]
Depends on https://github.com/bigshortbets/market-frontend/issues/8

**Comment by DanDanielD** [comment]
![image](https://github.com/user-attachments/assets/f4ff0e11-ec1f-4cbf-8498-3f66b107795c)
Regardless of order book depth, the fact that there are more orders than currently displayed (6 buy, 6 sell) should be indicated. At the moment, empty space in the order book windows causes a bit of confusion. Usually, this is resolved by filling the entire order book window with orders, leaving no empty space.

The most effective solution at the moment seems to be adding an additional line on both the buy and sell sides of the order book with '...' instead of price and quantity, as shown in the screenshot.
